from __future__ import annotations

from .deck_state import analyze_deck_state
from .runtime import CardIds, count_ids, damage_taken, energy_count


OBSERVATION_FEATURE_NAMES = [
    "hand_size",
    "deck_ratio",
    "my_prizes_left",
    "opponent_prizes_left",
    "prize_diff",
    "dwebble_in_play",
    "crustle_in_play",
    "kangaskhan_in_play",
    "active_energy",
    "active_damage",
    "opponent_active_energy",
    "opponent_active_damage",
    "opponent_active_is_ex",
    "needs_setup",
    "can_attack_now",
    "supporter_played",
    "energy_attached",
    "bench_space",
    "wall_online",
    "heal_window",
    "heal_prevents_ko",
    "bianca_window",
    "disruption_window",
    "gust_window",
    "gust_for_win",
    "gust_for_prize",
    "gust_for_stall",
    "active_is_crustle",
    "active_is_kangaskhan",
    "active_is_dwebble",
    "matchup_dragapult_ex",
    "matchup_mega_lucario",
    "matchup_unknown",
    "plan_finish",
    "plan_setup_backup",
    "plan_prevent_loss",
    "plan_setup_crustle_wall",
    "plan_protect_bench_core",
    "plan_wall_control",
    "plan_pressure_prize",
    "plan_resource_lock",
    "plan_kang_engine",
    "plan_stabilize",
    "has_hilda",
    "has_lillie",
    "has_petrel",
    "has_boss_orders",
    "has_eri",
    "has_xerosic",
    "has_jumbo_ice_cream",
    "has_bianca_devotion",
    "has_lisia",
    "has_poffin",
    "has_ultra_ball",
    "has_switch",
    "has_hand_trimmer",
    "has_hero_cape",
    "has_handheld_fan",
    "hand_growing_grass_count",
    "hand_mist_count",
    "hand_spiky_count",
    "hand_basic_grass_count",
    "discarded_dwebble_count",
    "discarded_crustle_count",
    "discarded_kangaskhan_count",
    "discarded_jumbo_count",
    "discarded_switch_count",
    "discard_growing_grass_count",
    "discard_mist_count",
    "discard_spiky_count",
    "discard_basic_grass_count",
]


def _has_card(counts, card_id: int) -> float:
    return 1.0 if counts[card_id] > 0 else 0.0


def build_observation_features(obs) -> list[float]:
    state = obs.current
    my_index = state.yourIndex
    my_state = state.players[my_index]
    op_state = state.players[1 - my_index]
    deck_state = analyze_deck_state(obs)
    active = my_state.active[0] if my_state.active else None
    opponent_active = op_state.active[0] if op_state.active else None
    field_counts = count_ids([card for card in my_state.active + my_state.bench if card is not None])
    hand_counts = count_ids(list(my_state.hand))
    discard_counts = count_ids(list(getattr(my_state, "discard", [])))
    return [
        len(my_state.hand) / 10.0,
        my_state.deckCount / 60.0,
        deck_state.my_prizes_left / 6.0,
        deck_state.opponent_prizes_left / 6.0,
        deck_state.prize_diff / 6.0,
        field_counts[CardIds.DWEBBLE] / 3.0,
        field_counts[CardIds.CRUSTLE] / 3.0,
        field_counts[CardIds.MEGA_KANGASKHAN_EX] / 3.0,
        energy_count(active) / 4.0,
        damage_taken(active) / 300.0 if active is not None else 0.0,
        energy_count(opponent_active) / 4.0,
        damage_taken(opponent_active) / 300.0 if opponent_active is not None else 0.0,
        1.0 if deck_state.opponent_active_is_ex else 0.0,
        1.0 if deck_state.needs_setup else 0.0,
        1.0 if deck_state.can_attack_now else 0.0,
        1.0 if state.supporterPlayed else 0.0,
        1.0 if state.energyAttached else 0.0,
        deck_state.bench_space / 5.0,
        1.0 if deck_state.wall_online else 0.0,
        1.0 if deck_state.heal_window else 0.0,
        1.0 if deck_state.heal_prevents_ko else 0.0,
        1.0 if deck_state.bianca_window else 0.0,
        1.0 if deck_state.disruption_window else 0.0,
        1.0 if deck_state.gust_window else 0.0,
        1.0 if deck_state.gust_for_win else 0.0,
        1.0 if deck_state.gust_for_prize else 0.0,
        1.0 if deck_state.gust_for_stall else 0.0,
        1.0 if deck_state.active_is_crustle else 0.0,
        1.0 if deck_state.active_is_kangaskhan else 0.0,
        1.0 if deck_state.active_is_dwebble else 0.0,
        1.0 if deck_state.matchup.name == "dragapult_ex" else 0.0,
        1.0 if deck_state.matchup.name == "mega_lucario" else 0.0,
        1.0 if deck_state.matchup.name == "unknown" else 0.0,
        min(1.0, deck_state.plan_scores.get("finish", 0.0)),
        min(1.0, deck_state.plan_scores.get("setup_backup", 0.0)),
        min(1.0, deck_state.plan_scores.get("prevent_loss", 0.0)),
        min(1.0, deck_state.plan_scores.get("setup_crustle_wall", 0.0)),
        min(1.0, deck_state.plan_scores.get("protect_bench_core", 0.0)),
        min(1.0, deck_state.plan_scores.get("wall_control", 0.0)),
        min(1.0, deck_state.plan_scores.get("pressure_prize", 0.0)),
        min(1.0, deck_state.plan_scores.get("resource_lock", 0.0)),
        min(1.0, deck_state.plan_scores.get("kang_engine", 0.0)),
        min(1.0, deck_state.plan_scores.get("stabilize", 0.0)),
        _has_card(hand_counts, CardIds.HILDA),
        _has_card(hand_counts, CardIds.LILLIE),
        _has_card(hand_counts, CardIds.PETREL),
        _has_card(hand_counts, CardIds.BOSS_ORDERS),
        _has_card(hand_counts, CardIds.ERI),
        _has_card(hand_counts, CardIds.XEROSIC),
        _has_card(hand_counts, CardIds.JUMBO_ICE_CREAM),
        _has_card(hand_counts, CardIds.BIANCA_DEVOTION),
        _has_card(hand_counts, CardIds.LISIA),
        _has_card(hand_counts, CardIds.BUDDY_BUDDY_POFFIN),
        _has_card(hand_counts, CardIds.ULTRA_BALL),
        _has_card(hand_counts, CardIds.SWITCH),
        _has_card(hand_counts, CardIds.HAND_TRIMMER),
        _has_card(hand_counts, CardIds.HERO_CAPE),
        _has_card(hand_counts, CardIds.HANDHELD_FAN),
        hand_counts[CardIds.GROW_GRASS_ENERGY] / 4.0,
        hand_counts[CardIds.MIST_ENERGY] / 4.0,
        hand_counts[CardIds.SPIKY_ENERGY] / 4.0,
        hand_counts[CardIds.BASIC_GRASS] / 6.0,
        discard_counts[CardIds.DWEBBLE] / 3.0,
        discard_counts[CardIds.CRUSTLE] / 3.0,
        discard_counts[CardIds.MEGA_KANGASKHAN_EX] / 3.0,
        discard_counts[CardIds.JUMBO_ICE_CREAM] / 2.0,
        discard_counts[CardIds.SWITCH] / 4.0,
        discard_counts[CardIds.GROW_GRASS_ENERGY] / 4.0,
        discard_counts[CardIds.MIST_ENERGY] / 4.0,
        discard_counts[CardIds.SPIKY_ENERGY] / 4.0,
        discard_counts[CardIds.BASIC_GRASS] / 6.0,
    ]
